routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('user/index');
});

// Authentication Routes...
$this->get('login', 'Auth\AuthController@showLoginForm');
$this->post('login', 'Auth\AuthController@login');
$this->get('logout', 'Auth\AuthController@logout');


// Password Reset Routes...
$this->get('password/reset/{token?}', 'Auth\PasswordController@showResetForm');
$this->post('password/email', 'Auth\PasswordController@sendResetLinkEmail');
$this->post('password/reset', 'Auth\PasswordController@reset');

Route::get('/home', 'HomeController@index');

Route::group([
	'middleware' => 'auth',
	'namespace' => 'Admin',
	'prefix' => 'admin',
	], function () {

		Route::get('/', function () {
        	return view('admin/index');
    	});

    	Route::resource('categories', 'CategoryController');
    	Route::resource('news', 'NewsController');
    	Route::get('news/{status?}/{category?}', 'NewsController@index');

    
});

app/Models/Category.php
<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\Category;
use App\Models\News;

class Category extends Model
{
	public function childs()
    {
        return $this->hasMany('App\Models\Category','parent_id');
    }

    public function parent()
    {
        return $this->belongsTo('App\Models\Category','parent_id');
    }

    public function news()
    {
        return $this->hasMany('App\Models\News');
    }

    public static  function selectArray($value=0,$id=0)
    {
        $catArray=[];
        if ($value==0) {
           $catArray[0]='';
        }
        
        $categories=Category::all();
        foreach ($categories as  $category) {
            if ($category->id!=$id) {
                $catArray[$category->id]=$category->name;
            }
        	
        }

        return $catArray;
    }

    public static  function buildMenu($parent=0)
    {  
        $result='';
        $categories=Category::all();
        
        foreach ($categories as $row){
            if ($row->parent_id == $parent){
                $url=url('/category/'.$row->id);
                $result.= '<li><a href="'.$url.'">'.$row->name .'</a>';
                if (count($row->childs)>0){
                    $result.= '<ul class="dropdown-menu" >';
                    $result.= Category::buildMenu($row->id);
                    $result.= '</ul>';
            }
            $result.= '</li>';
          }

      }

      

      return $result;

  }
    
}

app/Http/Controllers/Admin/CategoryController.php
<?php
namespace App\Http\Controllers\Admin;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\News;
class CategoryController extends Controller
{
       /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index()
    {
    	$categories=Category::all();
    	//dd($categories);
    	return view('admin/categories/index',['categories'=>$categories]);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
    	$categories=Category::selectArray();
    	return view('admin/categories/create',['categories'=>$categories]);
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */

    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|max:20',
            'description' => 'required',
        ]);
        $category = new Category;
        $category->name = $request->name;
        $category->description = $request->description;
        if( count(Category::find($request->parent))>0 )
        	$category->parent_id = $request->parent;
        $category->save();
        return redirect('admin/categories')->with('success', 1);
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        dd('show');    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::findOrFail($id);
    	$categories=Category::selectArray(0,$category->id);
        return view('admin/categories/edit', ['category' => $category,'categories'=>$categories]);
    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
    	$this->validate($request, [
            'name' => 'required|max:20',
            'description' => 'required',
        ]);
        $category =Category::find($id);
        $category->name = $request->name;
        $category->description = $request->description;
        if( count(Category::find($request->parent))>0 )
        	$category->parent_id = $request->parent;
        $category->save();
        return redirect('admin/categories')->with('success', 1);
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {   
        $news=Category::find($id)->news;
        foreach ($news as $item) {
            $item->category_id=NULL;
            $item->save();
        }
        Category::where('id', $id)->delete();
        return redirect('admin/categories');
    }
}

resources/views/admin/categories/create.blade.php
@extends('layouts.admin')

@section('title', 'კატეგორიები')
@section('maintitle', 'კატეგორიის დამატება')
@section('content')
{!! Form::open([

		'url' => '/admin/categories',
		'method'=>'POST',
		'class' => 'form-horizontal'

	]) !!}

      <div class="form-group">
          <label class="select2_multiple col-md-4 col-xs-12 control-label" >მშობელი</label>
          <div class="col-md-4 col-xs-12">   
        {!!
          Form::select(
            'parent',
            $categories,
            old('parent'),
            ['class'=>'form-control']
            
          )
        !!}    
        </div>
      </div>

      <div class="form-group">
         <label class="control-label col-md-4 col-xs-12">სახელი</label>
          <div class="col-md-4 col-xs-12">
              <input  type="text" class="form-control" value="{{ old('name') }}" name='name' placeholder="სახელი"
                data-validation="required" 
		 		data-validation-length="3-12" 
		 		data-validation-error-msg="სახელი აუცილებელია">
          </div>
      </div>

  		<div class="form-group">
         <label class="control-label col-md-4 col-xs-12">აღწერა</label>
          <div class="col-md-4 col-xs-12">
              <input type="text" class="form-control" value="{{ old('description') }}" name='description' placeholder="აღწერა"
               data-validation="required" 
		 	   data-validation-length="3-12" 
		       data-validation-error-msg="აღწერა აუცილებელია">
          </div>
      </div>
      
      <div class="form-group">
			  <label class="col-md-4 col-xs-12 control-label" for="singlebutton"></label>
			  <div class="col-md-4 col-xs-12">
			    <button type="submit" class="btn btn-success">დამატება</button>
			  </div>
	</div>
  {!! Form::close() !!}

@endsection
@push('scripts')
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.3.26/jquery.form-validator.min.js"></script>
<script>

  $.validate();


</script>
@endpush

resources/views/admin/categories/edit.blade.php
@extends('layouts.admin')

@section('title', 'კატეგორიები')
@section('maintitle', 'კატეგორიის შეცვლა')
@section('content')
@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
{!! Form::open([

		'url' => '/admin/categories/'.$category->id,
		'method'=>'PUT',
		'class' => 'form-horizontal'

	]) !!}

      <div class="form-group">
          <label class="select2_multiple col-md-4 col-xs-12 control-label" >მშობელი</label>
          <div class="col-md-4 col-xs-12">   
        {!!
          Form::select(
            'parent',
            $categories,
            old('parent',$category->parent_id),
            ['class'=>'form-control']
            
          )
        !!}    
        </div>
      </div>

      <div class="form-group">
         <label class="control-label col-md-4 col-xs-12">სახელი</label>
          <div class="col-md-4 col-xs-12">
              <input  type="text" class="form-control" value="{{ old('name',$category->name) }}" name='name' placeholder="სახელი"
                data-validation="required" 
		 		data-validation-length="3-12" 
		 		data-validation-error-msg="სახელი აუცილებელია">
          </div>
      </div>

  		<div class="form-group">
         <label class="control-label col-md-4 col-xs-12">აღწერა</label>
          <div class="col-md-4 col-xs-12">
              <input type="text" class="form-control" value="{{ old('description',$category->description) }}" name='description' placeholder="აღწერა"
               data-validation="required" 
		 	   data-validation-length="3-12" 
		       data-validation-error-msg="აღწერა აუცილებელია">
          </div>
      </div>
      
      <div class="form-group">
			  <label class="col-md-4 col-xs-12 control-label" for="singlebutton"></label>
			  <div class="col-md-4 col-xs-12">
			    <button type="submit" class="btn btn-success">შეცვლა</button>
			  </div>
	</div>
  {!! Form::close() !!}

@endsection
@push('scripts')
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.3.26/jquery.form-validator.min.js"></script>
<script>

  $.validate();


</script>
@endpush

resources/views/admin/categories/index.blade.php
@extends('layouts.admin')
@push('meta')
<meta name="csrf-token" content="<?= csrf_token() ?>" />
<meta name="csrf-param" content="_token" />
@endpush
@section('title', 'კატეგორიები')

@section('maintitle', 'კატეგორიები')
@section('content')

<table class="table table-bordered table-striped table-hover">
    <thead>
      <tr>
        <th>სახელი</th>
        <th>აღწერა</th>
        <th>მშობელი</th>
        <th></th>
        <th></th>

      </tr>
    </thead>
    <tbody>
    @foreach($categories as $category)
      <tr>
        <td>{{$category->name}}</td>
        <td>{{$category->description}}</td>
        <td>
        	@if(isset($category->parent))
        		{{$category->parent->name}}
        	@endif
        </td>
        <td>
        	<a href="{{url('admin/categories/'.$category->id.'/edit')}}"><span class="fa fa-pencil"></span></a>

        </td>
        <td>
        	<a href="{{ route('categories.destroy',array($category->id)) }}" data-method="delete" rel="nofollow" data-confirm="Are you sure you want to delete this?"><span class="fa fa-remove"></span></a>
        </td>
      </tr>
    @endforeach
    </tbody>
  </table>

@endsection
@push('scripts')
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-ujs/1.2.2/rails.min.js"></script>

@endpush