routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('user/index');
});

// Authentication Routes...
$this->get('login', 'Auth\AuthController@showLoginForm');
$this->post('login', 'Auth\AuthController@login');
$this->get('logout', 'Auth\AuthController@logout');


// Password Reset Routes...
$this->get('password/reset/{token?}', 'Auth\PasswordController@showResetForm');
$this->post('password/email', 'Auth\PasswordController@sendResetLinkEmail');
$this->post('password/reset', 'Auth\PasswordController@reset');

Route::get('/home', 'HomeController@index');

Route::group([
	'middleware' => 'auth',
	'namespace' => 'Admin',
	'prefix' => 'admin',
	], function () {

		Route::get('/', function () {
        	return view('admin/index');
    	});

    	Route::resource('categories', 'CategoryController');
    	Route::resource('news', 'NewsController');
    	Route::get('news/{status?}/{category?}', 'NewsController@index');

    
});

app/Models/News.php
<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\Category;

class News extends Model
{

	public function Category()
    {
        return $this->belongsTo('App\Models\Category');
    }

    public function getStatus()
    {
    	if ($this->status=='active') {
    		return 'აქტიური';
    	}

    	return 'პასიური';
    }

}

app/Http/Controllers/Admin/NewsController.php
<?php
namespace App\Http\Controllers\Admin;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Category;
use App\Models\News;
class NewsController extends Controller
{
       /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index($status='',$category='')

    {
        
        if (!empty($status)) {
            $news=News::where('status',$status)->get();
            $selectdeStatus=$status;
        }else{
            $news=News::all();
            $selectdeStatus='';
        }
        $categories=Category::selectArray(1);
    	return view('admin/news/index',['news'=>$news,'categories'=>$categories,'status'=>$selectdeStatus]);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories=Category::selectArray(1);
        return view('admin/news/create',['categories'=>$categories]);
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */

    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'image'=>'required'
            
        ]);
        $news=new News;
        if(!empty($request->image)){
            $destinationPath = public_path().'/uploads/images';
            $extensionImg = $request->image->getClientOriginalExtension();
            $fileNameImg = rand(11111,99999).'.'.$extensionImg;
            $request->image->move($destinationPath, $fileNameImg);
            $news->image=url('/uploads/images/'.$fileNameImg);
        }
        
        
        $news->name=$request->name;
        $news->category_id=$request->category;
        $news->status=$request->status;
        $news->content=$request->content;
        
        $news->save();
        return redirect('admin/news')->with('success', 1);

    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $news=News::findOrFail($id);
        $categories=Category::selectArray(1);
        return view('admin/news/edit', ['news' => $news,'categories'=>$categories]);
    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            //'image'=>'required',
            
        ]);
        $news=News::findOrFail($id);
        if(!empty($request->image)){
            $destinationPath = public_path().'/uploads/images';
            $extensionImg = $request->image->getClientOriginalExtension();
            $fileNameImg = rand(11111,99999).'.'.$extensionImg;
            $request->image->move($destinationPath, $fileNameImg);
            $news->image=url('/uploads/images/'.$fileNameImg);
        }
        
        
        $news->name=$request->name;
        $news->category_id=$request->category;
        $news->status=$request->status;
        $news->content=$request->content;
        
        $news->save();
        return redirect('admin/news')->with('success', 1);
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {   
        News::where('id', $id)->delete();
        return redirect('admin/news');
    }
}

resources/views/admin/news/create.blade.php
@extends('layouts.admin')
@section('title', 'სიახლე')
@push('styles')
<link rel="stylesheet" href="https://rawgit.com/enyo/dropzone/master/dist/dropzone.css">

@endpush
@section('maintitle', 'სიახლის დამატება')
@section('content')
{!! Form::open([

		'url' => '/admin/news',
		'method'=>'POST',
		'class' => 'form-horizontal',
		'files' => true

	]) !!}

      <div class="form-group">
          <label class="select2_multiple col-md-4 col-xs-12 control-label" >კატეგორია</label>
          <div class="col-md-4 col-xs-12">   
        {!!
          Form::select(
            'category',
            $categories,
            old('category'),
            ['class'=>'form-control',]
            
          )
        !!}    
        </div>
      </div>

      <div class="form-group">
         <label class="control-label col-md-4 col-xs-12">სტატუსი</label>
         <div class="col-md-4 col-xs-12">
         	<select class="form-control" name="status">
         		<option value="active">აქტიური</option>
         		<option value="passive">პასიური</option>
         	</select>
         </div> 
      </div>

      <div class="form-group">
         <label class="control-label col-md-4 col-xs-12">სათაური</label>
          <div class="col-md-4 col-xs-12">
              <input  type="text" class="form-control" value="{{ old('name') }}" name='name' placeholder="სახელი"
                data-validation="required" 
		 		data-validation-length="3-12" 
		 		data-validation-error-msg="სახელი აუცილებელია">
      		</div>

      </div>

      <div class="form-group">
         <label class="control-label col-md-4 col-xs-12">სურათი</label>
          <div class="col-md-4 col-xs-12">
	            <input type="file" class="form-control" name='image'>
	        </div>
      </div>

      


	  <div class="form-group">
         <label class="control-label col-md-4 col-xs-12">კონტენტი</label>
          <div class="col-md-4 col-xs-12">
          <textarea name="content"></textarea>
          </div>
      </div>

  		
      
      <div class="form-group">
			  <label class="col-md-4 col-xs-12 control-label" for="singlebutton"></label>
			  <div class="col-md-4 col-xs-12">
			    <button type="submit" class="btn btn-success">დამატება</button>
			  </div>
	</div>
  {!! Form::close() !!}

@endsection
@push('scripts')
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.3.26/jquery.form-validator.min.js"></script>
<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
<script src="https://rawgit.com/enyo/dropzone/master/dist/dropzone.js"></script>
<script>
tinymce.init({
 selector:'textarea',
 height : 300

 });

$.validate();

</script>
@endpush

resources/views/admin/news/edit.blade.php
@extends('layouts.admin')
@section('title', 'სიახლე')
@push('styles')
<link rel="stylesheet" href="https://rawgit.com/enyo/dropzone/master/dist/dropzone.css">

@endpush
@section('maintitle', 'სიახლის დამატება')
@section('content')
{!! Form::open([

		'url' => '/admin/news/'.$news->id,
		'method'=>'PUT',
		'class' => 'form-horizontal',
		'files' => true

	]) !!}

      <div class="form-group">
          <label class="select2_multiple col-md-4 col-xs-12 control-label" >კატეგორია</label>
          <div class="col-md-4 col-xs-12">   
        {!!
          Form::select(
            'category',
            $categories,
            old('category',$news->category_id),
            ['class'=>'form-control',]
            
          )
        !!}    
        </div>
      </div>

      <div class="form-group">
          <label class="select2_multiple col-md-4 col-xs-12 control-label" >კატეგორია</label>
          <div class="col-md-4 col-xs-12">   
        {!!
          Form::select(
            'status',
            [
            'active'=>'აქტიური',
             'pasive'=>'პასიური'
            ],
            old('status',$news->status),
            ['class'=>'form-control',]
            
          )
        !!}    
        </div>
      </div>

      <div class="form-group">
         <label class="control-label col-md-4 col-xs-12">სათაური</label>
          <div class="col-md-4 col-xs-12">
              <input  type="text" class="form-control" value="{{ old('name',$news->name) }}" name='name' placeholder="სახელი"
                data-validation="required" 
		 		data-validation-length="3-12" 
		 		data-validation-error-msg="სახელი აუცილებელია">
      		</div>

      </div>

      <div class="form-group">
         <label class="control-label col-md-4 col-xs-12">სურათი</label>
          <div class="col-md-4 col-xs-12">
	            <input type="file" class="form-control" name='image'>
	        </div>
      </div>

      


	  <div class="form-group">
         <label class="control-label col-md-4 col-xs-12">კონტენტი</label>
          <div class="col-md-4 col-xs-12">
          <textarea name="content" >{{ old('content',$news->content) }}</textarea>
          </div>
      </div>

  		
      
      <div class="form-group">
			  <label class="col-md-4 col-xs-12 control-label" for="singlebutton"></label>
			  <div class="col-md-4 col-xs-12">
			    <button type="submit" class="btn btn-success">რედაქტირება</button>
			  </div>
	</div>
  {!! Form::close() !!}

@endsection
@push('scripts')
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.3.26/jquery.form-validator.min.js"></script>
<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>

<script>
tinymce.init({
 selector:'textarea',
 height : 300,


 });

$.validate();

</script>
@endpush

resources/views/admin/news/index.blade.php
@extends('layouts.admin')
@push('meta')
<meta name="csrf-token" content="<?= csrf_token() ?>" />
<meta name="csrf-param" content="_token" />
@endpush
@section('title', 'სიახლეები')

@section('maintitle', 'სიახლეები')
@section('content')

 <div class="col-md-2 pull-right">
        {!!
            Form::select(
                'status',
                 [
                    'active'=>'აქტიური',
                    'pasive'=>'პასიური'
                ],
                $status,
                ['class' => 'form-control','id'=>'status']
            )
        !!}
</div>
 <div class="col-md-2 pull-right">
        {!!
            Form::select(
                'category',
                $categories,
                '',
                ['class' => 'form-control','id'=>'category']
            )
        !!}
</div>

<table class="table table-bordered table-striped table-hover" style="margin-top: 40px">
    <thead>
      <tr>
        <th>სათაური</th>
        <th>სტატუსი</th>
        <th>კატეგორია</th>
        <th>სურათი</th>
        <th></th>
        <th></th>

      </tr>
    </thead>
    <tbody>
    @foreach($news as $item)
      <tr>
        <td>{{$item->name}}</td>
        <td>{{$item->getStatus()}}</td>
        <td>
            @if(isset($item->category))
                {{$item->category->name}}
            @endif
        </td>
        <td><img src="{{$item->image}}" style="height: 60px;"></td>
        <td>
        	<a href="{{url('admin/news/'.$item->id.'/edit')}}"><span class="fa fa-pencil"></span></a>
        </td>
        <td>
        	<a href="{{ route('news.destroy',array($item->id)) }}" data-method="delete" rel="nofollow" data-confirm="Are you sure you want to delete this?"><span class="fa fa-remove"></span></a>
        </td>
      </tr>
    @endforeach
    </tbody>
  </table>

@endsection
@push('scripts')
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-ujs/1.2.2/rails.min.js"></script>
<script type="text/javascript">
    url='{{url('')}}'
    $( "#status" ).on('change',function() {

        my_url=url+"/admin/news/"+$(this).val();
        console.log(my_url);
        location.href=my_url;
    })
    $( "#category" ).on('change',function() {
        console.log($(this).val());
        my_url=url+"/admin/news/"+$(this).val();

        location.href=my_url;
    })
</script>
@endpush